// src_react/App.jsx
import { useEffect, useRef, useState } from "react";

export default function App() {
  const [state, setState] = useState({
    todoList: localSync(),
    todoInput: "",
  });

  useEffect(() => {
    localSync(true);
  },[state.todoList])

  function addTodo() {
    const todo = {
      id: Date.now(),
      status: false,
      todo: state.todoInput,
    };

    setState((prev) => ({ todoInput: "", todoList: [...prev.todoList, todo] }));
  }

  function deleteTodo(id){
    const updatedList = state.todoList.filter(todo => todo.id !== id);
    setState((prev) => ({...prev, todoList: updatedList}))
  }

  function toggleStatus(id){
    const index = state.todoList.findIndex(todo => todo.id == id);
    const updatedList = [...state.todoList];
    updatedList[index].status = !updatedList[index].status;
    setState((prev) => ({...prev, todoList: updatedList}))
  }

  function localSync(set = false){
    if(set){
      localStorage.setItem('todos', JSON.stringify(state.todoList));
      return state.todoList;
    }else{
      return JSON.parse(localStorage.getItem('todos') ?? "[]")
    }
  }

  return (
    <>
      <div className="container pt-14 mx-auto">
        <div className="actions flex justify-center pt-10">
          <input
            type="text"
            value={state.todoInput}
            onChange={(e) =>
              setState((prev) => ({ ...prev, todoInput: e.target.value }))
            }
            placeholder="Enter Todo Here"
            className=" outline-none rounded-md rounded-r-none px-2 py-1 w-1/2"
          />
          <button
            type="button"
            onClick={addTodo}
            className="px-5 py-1.5 rounded-l-none rounded-md bg-cyan-600 text-white"
          >
            Add
          </button>
        </div>

        <div className="todo-list w-2/3 mx-auto mt-8 flex flex-col gap-2">
          {state.todoList.map((todo) => {
            return (
              <div
                key={todo.id}
                className="todo flex w-full p-2 bg-cyan-800 text-white mx-auto items-center rounded-md"
              >
                <div className="status px-2 flex items-center">
                  <input
                    type="checkbox"
                    className="outline-none h-4 w-4 leading-none accent-cyan-400"
                    checked={todo.status}
                    onChange={() => toggleStatus(todo.id)}
                    name="status"
                    id="status"
                  />
                </div>
                <div className="title flex-1">
                  <p className={`max-w-full overflow-ellipsis ${todo.status ? 'line-through' : ''}`}  >{todo.todo}</p>
                </div>
                <div className="action px-2 text-black">
                  <button className="bg-rose-200 px-2 rounded-md" onClick={() => deleteTodo(todo.id)}>
                    Delete
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </>
  );
}

// src/app/app.component.ts
import { Component } from '@angular/core';

type TodoType = {
  id: number,
  todo: string,
  status: boolean,
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  mode: 'react' | 'angular' = 'angular';

  todoList:TodoType[] = this.localSync();

  addTodo(todoInput: HTMLInputElement){
    const todo:TodoType = {
      id: Date.now(),
      status: false,
      todo: todoInput.value
    }
    this.todoList.push(todo);
    todoInput.value = '';
    this.localSync(true);
  }

  localSync(set = false){
    if(set){
      localStorage.setItem('todos', JSON.stringify(this.todoList));
      return this.todoList;
    }else{
      return JSON.parse(localStorage.getItem('todos') ?? "[]")
    }
  }

  switchMode(newMode: 'react' | 'angular'){
    this.mode = newMode;
    if(newMode == 'react'){
      window.postMessage({type: 'start-react', from:'APP'})
    }else{
      window.postMessage({type: 'stop-react', from:'APP'})
    }
    this.todoList = this.localSync()
  }

  deleteTodo(id:number){
    this.todoList = this.todoList.filter(todo => todo.id !== id);
    this.localSync(true);
  }

  trackByTodo(index:number, todo: TodoType){
    return todo.id;
  }

}

<div class="ng-wrapper w-screen h-screen overflow-auto bg-rose-300" *ngIf="mode == 'angular'">
  <div class="container pt-14 mx-auto">
    <div class="actions flex justify-center pt-10">
      <input #todoInput type="text" placeholder="Enter Todo Here " class=" outline-none rounded-md rounded-r-none px-2 py-1 w-1/2">
      <button (click)="addTodo(todoInput)"  type="button" class="px-5 py-1.5 rounded-l-none rounded-md bg-rose-500 text-white">Add</button>
    </div>

    <div class="todo-list w-2/3 mx-auto mt-8 flex flex-col gap-2">
      <div *ngFor="let todo of todoList; trackBy:trackByTodo" class="todo flex w-full p-2 bg-cyan-800 text-white mx-auto items-center rounded-md">
        <div class="status px-2 flex items-center">
          <input type="checkbox" [(ngModel)]="todo.status" (ngModelChange)="localSync(true)"  class="outline-none h-4 w-4 leading-none accent-rose-400" name="status" id="status">
        </div>
        <div class="title flex-1">
          <p class="max-w-full overflow-ellipsis" [ngClass]="{strike: todo.status}" >{{todo.todo}}</p>
        </div>
        <div class="action px-2 text-black">
          <button class="bg-rose-200 px-2 rounded-md" (click)="deleteTodo(todo.id)">Delete</button>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="react-wrapper w-screen h-screen overflow-auto bg-cyan-700" *ngIf="mode == 'react'">
  <div id="react-root"></div>
</div>

<div class="switch-wrapper fixed top-2 left-1/2 -translate-x-1/2 z-10">
  <div
    class="switch flex items-center justify-center rounded-md shadow-md divide-x-2 overflow-hidden"
  >
    <button
      class="p-2 w-20 bg-rose-600/40 text-white transition-colors duration-300"
      [ngClass]="{ rose: mode == 'angular' }"
      (click)="switchMode('angular')"
    >
      Angular
    </button>
    <button
      class="p-2 w-20 bg-cyan-600/40 text-white transition-colors duration-300"
      [ngClass]="{ cyan: mode == 'react' }"
      (click)="switchMode('react')"
    >
      React
    </button>
  </div>
</div>
